### ISSUE TITLE
maturity notice

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/RAD.IMR#16]
As discussed on the DCC... there are a few ways to inform your reader that the IG is less mature than other IG might be.

alternatives in individual comments

**Comment by JohnMoehrke** [comment]
Use the IG publisher capability to add a FMM decoration. This appears in the IG xml as well as on page one of the narrative

In the sushi-config.yaml add the following, where the number given is 0-5, should for now follow the HL7 definitions for FMM.

```
extension: 
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 0

```
